### ISSUE TITLE
change the figure field

### ISSUE THREAD

**Issue by shj37** [tomwalker/django_quiz#36]
I try to drop the figure field in multiple-choice and replace it with a new charfield figure_url to save url of figure saved in another website (I also changed admin and template accordingly). First, I ran "python manage.py makemigrations + migrate", no migration applied, then I used "python manage.py makemigrations quiz + migrate". Got the following message for failing of running migration. Thanks.

Operations to perform:
  Synchronize unmigrated apps: django_markdown, staticfiles, multichoice, smart_selects, messages, true_false, crispy_fo
rms, mptt, essay
  Apply all migrations: rango, sites, quiz, tagging, admin, registration, contenttypes, auth, biology, blog, sessions, d
jango_comments, zinnia, flatpages
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Shijun\Desktop\rango\rango\lib\site-packages\django\core\management\__init__.py", line 338, in execute_
from_command_line
    utility.execute()
  File "C:\Users\Shijun\Desktop\rango\rango\lib\site-packages\django\core\management\__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Shijun\Desktop\rango\rango\lib\site-packages\django\core\management\base.py", line 390, in run_from_arg
v
    self.execute(*args, **cmd_options)
  File "C:\Users\Shijun\Desktop\rango\rango\lib\site-packages\django\core\management\base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Shijun\Desktop\rango\rango\lib\site-packages\django\core\management\commands\migrate.py", line 221, in
handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Shijun\Desktop\rango\rango\lib\site-packages\django\db\migrations\executor.py", line 100, in migrate
    state.apps  # Render all real_apps -- performance critical
  File "C:\Users\Shijun\Desktop\rango\rango\lib\site-packages\django\utils\functional.py", line 60, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Shijun\Desktop\rango\rango\lib\site-packages\django\db\migrations\state.py", line 166, in apps
    return StateApps(self.real_apps, self.models)
  File "C:\Users\Shijun\Desktop\rango\rango\lib\site-packages\django\db\migrations\state.py", line 232, in __init__
    self.render_multiple(list(models.values()) + self.real_models)
  File "C:\Users\Shijun\Desktop\rango\rango\lib\site-packages\django\db\migrations\state.py", line 270, in render_multip
le
    "for more" % (new_unrendered_models, get_docs_version())
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'multichoice.MCQuestion'>, <ModelSt
ate: 'true_false.TF_Question'>, <ModelState: 'essay.Essay_Question'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.8/topics/migrations/#dependencies for more

**Comment by shj37** [comment]
I guess a more straightforward question is how to make migrations after modifying the original model.
