### ISSUE TITLE
Installation from PyPI lacks README

### ISSUE THREAD

**Issue by pydanny** [tomwalker/django_quiz#37]
On Python 2.7, 3.4, and 3.5 I get this error when I try to install from PyPI:

```
$ pip install django-quiz-app
Collecting django-quiz-app
  Downloading django-quiz-app-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/h_/rdtpztvj4c9cfg2ctqyp_wl40000gp/T/pip-build-h8rl1rpd/django-quiz-app/setup.py", line 3, in <module>
        readme = open('README.rst').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/h_/rdtpztvj4c9cfg2ctqyp_wl40000gp/T/pip-build-h8rl1rpd/django-quiz-app
```

It's really strange, because your `MANIFEST.in` includes the README.rst file that's breaking the install.

**Comment by d0ugal** [comment]
I guess something went wrong with the upload to PyPI somehow. I checked out the repo, ran `python setup.py sdist` and then extracted the archive created in dist and it contained both the README files. So just re-releasing it should work.

There don't seem to be any tags or branches in git for me to test the sha uploaded to pypi, it might be a good idea to do that.

**Comment by tomwalker** [comment]
Thanks for pointing that out.

Il try and get that re-uploaded today and tag it for the future as well.
