### ISSUE TITLE
Starting the project

### ISSUE THREAD

**Issue by stonetwig** [tomwalker/django_quiz#70]
Yow,

I downloaded the project and installed it like the readme told me.
However, I can't run any migration or run the server locally using django-admin. Isn't the project meant to have a `manage.py`?

If someone could elaborate on how to actually run the project when downloaded and installed it would be great. I am currently evaluating this project for a client and if it suits our initial needs we could spend some hours contributing to this project.

Here is the error when I try to run the project (on windows):
```
PS C:\Users\myuser\Documents\Code\django_quiz> django-admin runserver
Traceback (most recent call last):
  File "C:\Python36\Scripts\django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "c:\python36\lib\site-packages\django\core\management\__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "c:\python36\lib\site-packages\django\core\management\__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "c:\python36\lib\site-packages\django\core\management\__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "c:\python36\lib\site-packages\django\core\management\__init__.py", line 75, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "c:\python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "c:\python36\lib\site-packages\django\core\management\commands\runserver.py", line 12, in <module>
    from django.core.servers.basehttp import run, get_internal_wsgi_application
  File "c:\python36\lib\site-packages\django\core\servers\basehttp.py", line 20, in <module>
    from django.core.wsgi import get_wsgi_application
  File "c:\python36\lib\site-packages\django\core\wsgi.py", line 1, in <module>
    from django.core.handlers.wsgi import WSGIHandler
  File "c:\python36\lib\site-packages\django\core\handlers\wsgi.py", line 11, in <module>
    from django.core.handlers import base
  File "c:\python36\lib\site-packages\django\core\handlers\base.py", line 16, in <module>
    from django.views import debug
  File "c:\python36\lib\site-packages\django\views\debug.py", line 12, in <module>
    from django.template import Template, Context, TemplateDoesNotExist
  File "c:\python36\lib\site-packages\django\template\__init__.py", line 53, in <module>
    from django.template.base import (ALLOWED_VARIABLE_CHARS, BLOCK_TAG_END,
  File "c:\python36\lib\site-packages\django\template\base.py", line 19, in <module>
    from django.utils.html import escape
  File "c:\python36\lib\site-packages\django\utils\html.py", line 14, in <module>
    from .html_parser import HTMLParser, HTMLParseError
  File "c:\python36\lib\site-packages\django\utils\html_parser.py", line 12, in <module>
    HTMLParseError = _html_parser.HTMLParseError
```
Do I simply use too new of a Python version?

Best wishes,
Markus

**Comment by iustitia** [comment]
Hey Markus,

There is some incompability between Python and Django versions. Try to upgrade Django to 1.8 at least (1.10 will give you some other problems, discussed in other thread). More about the problem: http://stackoverflow.com/questions/34827566/attributeerror-module-html-parser-has-no-attribute-htmlparseerror

Well, the project is only a library, so no manage.py. You can use it in your own project and add as an app, but you can't run it by itself.

Hope this helps.

**Comment by stonetwig** [comment]
Hey,

Thanks for the answer. I created my own django project, upgraded the requirement to be 1.8 and it worked perfectly. Thanks.
